import { packagedContentSchema, type PackagedContent } from '../domain/content.schemas';

export const PACKAGED_CONTENT_VERSION = 2;

const content: PackagedContent = {
  version: PACKAGED_CONTENT_VERSION,
  sections: [
    {
      id: 'section-translating-verbal-expressions',
      title: 'Translating Verbal Expressions',
      description: 'Learn how mathematical operations appear in everyday language.',
      displayOrder: 1,
      contentVersion: 1,
    },
  ],
  units: [
    {
      id: 'unit-operation-words',
      sectionId: 'section-translating-verbal-expressions',
      title: 'Operation Words',
      description: 'Recognize operation signals and preserve the intended order.',
      displayOrder: 1,
      contentVersion: 1,
    },
  ],
  lessons: [
    {
      id: 'lesson-operation-signals',
      sectionId: 'section-translating-verbal-expressions',
      unitId: 'unit-operation-words',
      title: 'Words That Signal Operations',
      shortDescription:
        'Connect common verbal phrases with addition, subtraction, multiplication, and division.',
      concepts: ['Operation keywords', 'Verbal expressions', 'Order-sensitive phrases'],
      displayOrder: 1,
      contentStatus: 'playable',
      passingThreshold: 70,
      contentVersion: 1,
      instructionalContent: [
        {
          id: 'intro-operation-signals',
          type: 'paragraph',
          title: 'Words can signal an operation',
          body: 'A verbal expression describes mathematics using words. Signal words help us decide which operation to use, but we must also read the order carefully.',
        },
        {
          id: 'example-sum',
          type: 'example',
          phrase: 'the sum of a number and five',
          expression: 'n + 5',
          note: 'Sum, plus, added to, and increased by commonly signal addition.',
        },
        {
          id: 'example-difference',
          type: 'example',
          phrase: 'the difference of twelve and a number',
          expression: '12 − n',
          note: 'Difference and minus signal subtraction. Keep the named order.',
        },
        {
          id: 'example-product',
          type: 'example',
          phrase: 'the product of three and a number',
          expression: '3n',
          note: 'Product, times, multiplied by, and of can signal multiplication.',
        },
        {
          id: 'example-quotient',
          type: 'example',
          phrase: 'the quotient of a number and four',
          expression: 'n ÷ 4',
          note: 'Quotient, divided by, and per can signal division. Order matters.',
        },
        {
          id: 'warning-less-than',
          type: 'warning',
          title: 'Watch “less than” and “subtracted from”',
          body: 'These phrases reverse the apparent order: “six less than a number” is n − 6, and “a number subtracted from twelve” is 12 − n.',
        },
      ],
      activities: [
        {
          id: 'find-sum',
          type: 'find-word',
          title: 'Find the addition word',
          prompt: 'Choose the word that makes the verbal phrase match the expression.',
          mathStatement: '8 + n',
          sentenceBefore: 'The',
          sentenceAfter: 'of eight and a number',
          choices: [
            { id: 'sum', label: 'sum' },
            { id: 'difference', label: 'difference' },
            { id: 'product', label: 'product' },
          ],
          correctChoiceId: 'sum',
          hint: { body: 'Which operation does the plus sign show?' },
          explanation: {
            title: 'Correct word: sum',
            body: '“Sum” names the result of addition, so the sum of eight and a number is 8 + n.',
          },
        },
        {
          id: 'find-product',
          type: 'find-word',
          title: 'Find the multiplication word',
          prompt: 'Choose the operation word that describes the expression.',
          mathStatement: '5x',
          sentenceBefore: 'The',
          sentenceAfter: 'of five and a number',
          choices: [
            { id: 'quotient', label: 'quotient' },
            { id: 'product', label: 'product' },
            { id: 'difference', label: 'difference' },
          ],
          correctChoiceId: 'product',
          hint: { body: 'A number written beside a variable means multiplication.' },
          explanation: {
            title: 'Correct word: product',
            body: '“Product” signals multiplication. The product of five and x is 5x.',
          },
        },
        {
          id: 'find-quotient',
          type: 'find-word',
          title: 'Find the division word',
          prompt: 'Complete the phrase so it describes the expression precisely.',
          mathStatement: 'n ÷ 4',
          sentenceBefore: 'The',
          sentenceAfter: 'of a number and four',
          choices: [
            { id: 'sum', label: 'sum' },
            { id: 'quotient', label: 'quotient' },
            { id: 'product', label: 'product' },
          ],
          correctChoiceId: 'quotient',
          hint: { body: 'The expression divides a number by four.' },
          explanation: {
            title: 'Correct word: quotient',
            body: '“Quotient” names a division result. The quotient of n and 4 keeps n first: n ÷ 4.',
          },
        },
        {
          id: 'organize-less-than',
          type: 'organize-translate',
          title: 'Put “less than” in order',
          prompt: 'Build the verbal phrase that matches the expression.',
          mathStatement: 'n − 6',
          tokens: [
            { id: 'number', label: 'a number' },
            { id: 'six', label: 'six' },
            { id: 'less-than', label: 'less than' },
          ],
          correctTokenSequence: ['six', 'less-than', 'number'],
          hint: { body: 'Read n − 6 as six fewer than n.' },
          explanation: {
            title: 'Order reversed correctly',
            body: '“Six less than a number” means begin with the number, then subtract six: n − 6.',
          },
        },
        {
          id: 'organize-subtracted-from',
          type: 'organize-translate',
          title: 'Translate “subtracted from”',
          prompt: 'Arrange every token into a mathematically precise phrase.',
          mathStatement: '12 − y',
          tokens: [
            { id: 'twelve', label: 'twelve' },
            { id: 'a-number', label: 'a number' },
            { id: 'subtracted-from', label: 'subtracted from' },
          ],
          correctTokenSequence: ['a-number', 'subtracted-from', 'twelve'],
          hint: { body: 'The quantity after “from” is written first in the expression.' },
          explanation: {
            title: '“From” changes the order',
            body: '“A number subtracted from twelve” starts with twelve and removes the number: 12 − y.',
          },
        },
        {
          id: 'organize-sum-product',
          type: 'organize-translate',
          title: 'Combine two operation signals',
          prompt: 'Build the complete phrase for the expression.',
          mathStatement: '3m + 7',
          tokens: [
            { id: 'seven', label: 'seven' },
            { id: 'and', label: 'and' },
            { id: 'three-times', label: 'three times a number' },
            { id: 'sum-of', label: 'the sum of' },
          ],
          correctTokenSequence: ['sum-of', 'three-times', 'and', 'seven'],
          hint: { body: 'Name the outer addition first, then describe both terms.' },
          explanation: {
            title: 'Two signals, one expression',
            body: '“The sum of” joins 3m and 7. “Three times a number” describes the product 3m.',
          },
        },
      ],
    },
    {
      id: 'lesson-order-matters',
      sectionId: 'section-translating-verbal-expressions',
      unitId: 'unit-operation-words',
      title: 'Order Matters',
      shortDescription: 'Practice phrases whose word order changes the mathematical expression.',
      concepts: ['Less than', 'Subtracted from', 'More than', 'Difference in named order'],
      displayOrder: 2,
      prerequisiteLessonId: 'lesson-operation-signals',
      contentStatus: 'playable',
      passingThreshold: 70,
      contentVersion: 2,
      instructionalContent: [
        {
          id: 'intro-order-sensitive-phrases',
          type: 'paragraph',
          title: 'Read order-sensitive phrases carefully',
          body: 'Some verbal phrases name quantities in a different order from the mathematical expression. Identify the operation phrase, then decide which quantity must be written first.',
        },
        {
          id: 'example-six-less-than',
          type: 'example',
          phrase: 'six less than a number',
          expression: 'n − 6',
          note: '“Less than” subtracts the first quantity from the quantity named afterward.',
        },
        {
          id: 'example-subtracted-from-twelve',
          type: 'example',
          phrase: 'a number subtracted from twelve',
          expression: '12 − n',
          note: '“Subtracted from” reverses the apparent spoken order.',
        },
        {
          id: 'example-four-more-than-twice',
          type: 'example',
          phrase: 'four more than twice a number',
          expression: '2n + 4',
          note: '“More than” adds to the quantity named afterward.',
        },
        {
          id: 'example-difference-twelve-number',
          type: 'example',
          phrase: 'the difference of twelve and a number',
          expression: '12 − n',
          note: '“The difference of A and B” preserves the named order as A − B.',
        },
        {
          id: 'warning-check-subtraction-order',
          type: 'warning',
          title: 'Check which quantity comes first',
          body: 'For “less than” and “subtracted from,” the quantity named afterward is written first. “More than” adds to the quantity named afterward. “The difference of A and B” keeps A first and B second.',
        },
      ],
      activities: [
        {
          id: 'order-find-less-than',
          type: 'find-word',
          title: 'Find the order-sensitive word',
          prompt: 'Choose the word that makes the phrase match the expression.',
          mathStatement: 'n − 6',
          sentenceBefore: 'Six',
          sentenceAfter: 'than a number',
          choices: [
            { id: 'less', label: 'less' },
            { id: 'more', label: 'more' },
            { id: 'times', label: 'times' },
          ],
          correctChoiceId: 'less',
          hint: { body: 'Start with n and subtract six.' },
          explanation: {
            title: 'Correct word: less',
            body: '“Six less than a number” means start with n and subtract six: n − 6.',
          },
        },
        {
          id: 'order-find-subtracted-from',
          type: 'find-word',
          title: 'Find the reversal phrase',
          prompt: 'Choose the word that makes the phrase match the expression.',
          mathStatement: '12 − n',
          sentenceBefore: 'A number',
          sentenceAfter: 'from twelve',
          choices: [
            { id: 'added', label: 'added' },
            { id: 'subtracted', label: 'subtracted' },
            { id: 'multiplied', label: 'multiplied' },
          ],
          correctChoiceId: 'subtracted',
          hint: { body: 'The quantity after “from” is written first.' },
          explanation: {
            title: 'Correct word: subtracted',
            body: '“A number subtracted from twelve” starts with twelve and removes n, so it is 12 − n, not n − 12.',
          },
        },
        {
          id: 'order-organize-less-than',
          type: 'organize-translate',
          title: 'Order a less-than phrase',
          prompt: 'Arrange the tokens into the phrase that matches the expression.',
          mathStatement: 'n − 5',
          tokens: [
            { id: 'number', label: 'a number' },
            { id: 'less-than', label: 'less than' },
            { id: 'five', label: 'five' },
          ],
          correctTokenSequence: ['five', 'less-than', 'number'],
          hint: { body: 'The phrase begins with the amount being subtracted.' },
          explanation: {
            title: 'The number after “less than” comes first',
            body: '“Five less than a number” is n − 5 because the value following “less than” comes first in the expression.',
          },
        },
        {
          id: 'order-organize-subtracted-from',
          type: 'organize-translate',
          title: 'Order a subtracted-from phrase',
          prompt: 'Arrange the tokens into the phrase that matches the expression.',
          mathStatement: '12 − n',
          tokens: [
            { id: 'twelve', label: 'twelve' },
            { id: 'subtracted-from', label: 'subtracted from' },
            { id: 'a-number', label: 'a number' },
          ],
          correctTokenSequence: ['a-number', 'subtracted-from', 'twelve'],
          hint: { body: '“From twelve” tells you that twelve is written first.' },
          explanation: {
            title: '“Subtracted from” reverses the order',
            body: '“A number subtracted from twelve” means begin with twelve, then subtract n: 12 − n.',
          },
        },
        {
          id: 'order-organize-more-than',
          type: 'organize-translate',
          title: 'Order a more-than phrase',
          prompt: 'Arrange the tokens into the phrase that matches the expression.',
          mathStatement: '2n + 4',
          tokens: [
            { id: 'twice-number', label: 'twice a number' },
            { id: 'four', label: 'four' },
            { id: 'more-than', label: 'more than' },
          ],
          correctTokenSequence: ['four', 'more-than', 'twice-number'],
          hint: { body: 'First identify 2n, then add four.' },
          explanation: {
            title: 'Add four to twice the number',
            body: '“Twice a number” is 2n. “Four more than” tells us to add four, giving 2n + 4.',
          },
        },
      ],
    },
  ],
};

export const packagedContent = packagedContentSchema.parse(content);
